from enum import IntEnum
import asyncio

class Direction(IntEnum):
    CLIENT = 0
    SERVER = 1


class Packets(IntEnum):
    PROTOCOL_VERSION = 0
    CONNECT_RESPONSE = 1
    SERVER_DISCONNECT = 2
    HANDSHAKE_CHALLENGE = 3
    CHAT_RECEIVED = 4
    UNIVERSE_TIME_UPDATE = 5
    CLIENT_CONNECT = 6
    CLIENT_DISCONNECT = 7
    HANDSHAKE_RESPONSE = 8
    WARP_COMMAND = 9
    CHAT_SENT = 10
    CLIENT_CONTEXT_UPDATE = 11
    WORLD_START = 12
    WORLD_STOP = 13
    TILE_ARRAY_UPDATE = 14
    TILE_UPDATE = 15
    TILE_LIQUID_UPDATE = 16
    TILE_DAMAGE_UPDATE = 17
    TILE_MODIFICATION_FAILURE = 18
    GIVE_ITEM = 19
    SWAP_IN_CONTAINER_RESULT = 20
    ENVIRONMENT_UPDATE = 21
    ENTITY_INTERACT_RESULT = 22
    MODIFY_TILE_LIST = 23
    DAMAGE_TILE = 24
    DAMAGE_TILE_GROUP = 25
    REQUEST_DROP = 26
    SPAWN_ENTITY = 27
    ENTITY_INTERACT = 28
    CONNECT_WIRE = 29
    DISCONNECT_ALL_WIRES = 30
    OPEN_CONTAINER = 31
    CLOSE_CONTAINER = 32
    SWAP_IN_CONTAINER = 33
    ITEM_APPLY_IN_CONTAINER = 34
    START_CRAFTING_IN_CONTAINER = 35
    STOP_CRAFTING_IN_CONTAINER = 36
    BURN_CONTAINER = 37
    CLEAR_CONTAINER = 38
    WORLD_UPDATE = 39
    ENTITY_CREATE = 40
    ENTITY_UPDATE = 41
    ENTITY_DESTROY = 42
    DAMAGE_NOTIFICATION = 43
    STATUS_EFFECT_REQUEST = 44
    UPDATE_WORLD_PROPERTIES = 45
    HEARTBEAT = 46


class EntityType(IntEnum):
    END = -1
    PLAYER = 0
    MONSTER = 1
    OBJECT = 2
    ITEMDROP = 3
    PROJECTILE = 4
    PLANT = 5
    PLANTDROP = 6
    EFFECT = 7
